### ISSUE TITLE
Allow defining full path to Git repository for components

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#73]
Enable Commodore to use components which are hosted in different repositories. This will likely require some reworking of the current component discovery mechanism, which relies on the `COMMODORE_GLOBAL_GIT_BASE` configuration to actually clone component repositories.

### Task deliverables
- [x] Commodore can clone components hosted on different Git services
- [x] A Git base URL is configured as a default for components
- [x] Overrides can be specified for single components in the config file (`commodore.yml`)
- [ ] In addition, component_versions can be used to change the URL for a component in the hierarchy

**Comment by srueg** [comment]
As discussed, I'll write the SDD with the following idea:
1. A Git base URL is still configured as a default for components
2. Overrides can be specified for single components in the config file (same as in https://github.com/projectsyn/commodore/issues/93)
3. In addition, `component_versions` can be used to change the URL for a component in the hierarchy (only in addition to the global config though).
