### ISSUE TITLE
Simplify running Commodore locally

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#76]
Currently, running Commodore locally can be a bit tricky. The docker image is PoC quality at best, in particular with regard to how SSH credentials are handled and running Commodore via Pipenv requires a fair amount of setup on the local machine. Currently the Pipenv dependencies seem to be incomplete on OS X, further complicating the local setup.

Consider providing the option to have Commodore use deploy keys to clone repositories from various Git hosting platforms. Alternatively consider providing a way to "forward" the local ssh agent on the host into the docker container.

A third option to consider (in conjunction with #70) is to provide Commodore as a package on PyPI for users to install.

### Task deliverables
- [ ] Make running Commodore while developing components as straight-forward as possible
- [ ] Create good documentation on how to setup Commodore locally
- [ ] Verify that Commodore can be executed locally on Linux and OS X without any manual adjustments

**Comment by simu** [comment]
Further notes regarding running the PoC docker image:
* You need to run `export HOME=/app` for `commodore new-component` to work
* depending on whether the directories mounted in the container are owned by the container UID (1001) or not, cloning the config and dependencies may not work

**Comment by Kidswiss** [comment]
* make `kapitan.libjsonnet`available in `dependencies/lib` that so that https://marketplace.visualstudio.com/items?itemName=heptio.jsonnet can render the jsonnet files locally

**Comment by srueg** [comment]
Dockerfile improved and adding a docker-compose setup: https://github.com/projectsyn/commodore/pull/99

**Comment by simu** [comment]
Since #376, commodore can be installed from PyPI on both Linux and macOS. We no longer need to build the Kapitan Helm bindings, but instead users just need to install helm binaries, as documented in https://syn.tools/commodore/explanation/running-commodore.html

We've briefly looked at building distribution packages, but since various Python dependencies used by Kapitan and Commodore are not available in the distribution repos, the effort to build packages vastly outweighs the benefit we'd get from them.
